name: Publish Library

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew :JetAds:build --warning-mode all

      - name: Start Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          disable-linux-hw-accel: true
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: Nexus 6P
          script: ./gradlew :app:connectedAndroidTest --info

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
          SONATYPE_HOST: ${{ secrets.SONATYPE_HOST }}
          RELEASE_SIGNING_ENABLED: true
          SONATYPE_AUTOMATIC_RELEASE: true
        run: |
          ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache --info