name: Publish Library

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Import GPG key
        env:
          GPG_SECRET_KEY_RING_FILE_BASE64: ${{ secrets.GPG_SECRET_KEY_RING_FILE_BASE64 }}
        run: |
          echo "$GPG_SECRET_KEY_RING_FILE_BASE64" | base64 -d | gpg --import --batch

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set release version
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          echo "Raw GITHUB_REF: $GITHUB_REF"
          echo "Extracted RELEASE_VERSION: $RELEASE_VERSION"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          ESCAPED_VERSION=$(printf '%s\n' "$RELEASE_VERSION" | sed -e 's/[\/&]/\\&/g')
          echo "Escaped version: $ESCAPED_VERSION"
          sed -i "s/^version=.*/version=$ESCAPED_VERSION/" gradle.properties
          echo "Contents of gradle.properties after sed:"
          cat gradle.properties

      - name: Build with Gradle
        run: ./gradlew :JetAds:build

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          GPG_SECRET_KEY_RING_FILE: ${{ github.workspace }}/secring.gpg
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JetAds/build/outputs/aar/JetAds-release.aar
          asset_name: jet-ads-${{ env.RELEASE_VERSION }}.aar
          asset_content_type: application/aar