name: Publish Library

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      # Configure Gradle Cache para acelerar builds
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Decode GPG key
        env:
          GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY_RING_FILE_BASE64 }}
        run: |
          echo $GPG_SECRET_KEY | base64 --decode > ./secret.gpg

      - name: Set release version
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          sed -i "s/^version=.*/version=$RELEASE_VERSION/" gradle.properties

      - name: Build with Gradle
        run: ./gradlew :JetAds:build

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ./secret.gpg
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./JetAds/build/outputs/aar/JetAds-release.aar
          asset_name: jet-ads-${{ env.RELEASE_VERSION }}.aar
          asset_content_type: application/aar